### ISSUE TITLE
#1

### ISSUE THREAD

**Issue by octopus4** [ProstoKostik/InformationSecurityRSA#1]
1. Не использовать метки и прочие вещи из System.Windows.Forms в классе, который станет библиотечным.
2. НАХУЯ БЛЯТЬ ВОЗВРАЩАТЬ СТРИНГБИЛДЕР, КОТОРЫЙ В СЕБЕ СОДЕРЖИТ ОДНУ СТРОКУ КОТОРУЮ МОЖНО ПОЛУЧИТЬ ИНТЕРПОЛЯЦИЕЙ СТРОКИ Я ВООБЩЕ НЕ ПОНИМАЮ НАХУЙ
3. Алгоритм периодически глючит и фейлит проверку одной и той же строки.

**Comment by discorpsee** [comment]
2. че бы нет, не все сразу профессионалы, мне кто-то доказывал что при return final блок не будет исполняться )

**Comment by RznNike** [comment]
@discorpsee ага, а кто-то гитигнор настраивать не умеет -_-

**Comment by ProstoKostik** [comment]
ага, а кто-то в очко долбится -_-

**Comment by RznNike** [comment]
@ProstoKostik че ты такой агрессивный, про гитигнор я некиту ващет

**Comment by RznNike** [comment]
вроде это всё исправлено

**Comment by discorpsee** [comment]
и так сойдет
